services:
  nodeserver:
    restart: always
    build:
      context: ./backend
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    env_file: ./backend/.env
    environment:
      - PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DATABASE_URL

  db:
    restart: always
    build:
      context: ./database
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data

  reactserver:
    restart: always
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  nginxreverseproxy:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nodeserver
      - reactserver

  devadminer:
    restart: always
    image: adminer:latest
    container_name: devadminer
    ports:
      - "8081:8081"
    command:
      [
        "php",
        "-S",
        "0.0.0.0:8081",
        "-t",
        "/var/www/html",
        "/var/www/html/index.php",
      ]
    depends_on:
      - db

volumes:
  db-data:
